# name: hello world
# on:
#   push:
#      branches:
#        [main]
# jobs:
#   say-hello:
#     runs-on: ubuntu-
#     steps
#       - run: echo Hello
name: Run Python hello-world

on:

  workflow_dispatch:


jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: execute py Script
        env:
          SOME_SECRET: ${{secrets.SOME_SECRET}}
        run: python main.py

      - name: Run Python Script
        run: |
          python -m pip install pyTelegramBotAPI
          python -m pip install telepot
          python -m pip install opencv-python
          python -m pip install numpy
